import Support from "../../../component/supportDiv/index";
import supportImg from "../../../assets/img/support.svg";
import whtsAppImg from "../../../assets/img/whtsapp.svg";
import skype from "../../../assets/img/skype.svg";
import telegram from "../../../assets/img/telegram.svg";
import insta from "../../../assets/img/insta.svg";
import betFair from "../../../assets/img/betfair.png";
import Social from "../../../component/socialDiv/index";
import chromeIcon from "../../../assets/img/chromeIcon.png";
import app from "../../../assets/img/app2.png";
import downIos from "../../../assets/img/down-ios.png";
/////styles
import "./styles.scss";

import { useMediaQuery } from "../../../component/useMedia";
const FooterComponent = () => {
  const isMobile = useMediaQuery("(min-width: 1280px)");
  return (
    <div className="footer-container">
      <div className="top-footer-col">
        <div className="support-div">
          <Support
            img={supportImg}
            name1="Customer support1"
            name2="support2"
            bg="#fff"
            color="rgba(0, 0, 0, 0.5)"
          />
          <Support
            img={whtsAppImg}
            name1="WhatsApp 3"
            name2="WhatsApp 4"
            bg="#fff"
            color="rgba(0, 0, 0, 0.5)"
          />
        </div>
        <div className="social-div">
          <Social
            img={skype}
            name={isMobile ? "skyexchangeofficial" : "Skype"}
            bg="#fff"
            color="rgba(0, 0, 0, 0.5)"
            width="33%"
          />
          <Social
            img={telegram}
            name={isMobile ? "info@skyexchange.com" : "Email"}
            bg="#fff"
            color="rgba(0, 0, 0, 0.5)"
            width="33%"
          />
          <Social
            img={insta}
            name={isMobile ? "officialskyexchange" : "instagram"}
            bg="#fff"
            color="rgba(0, 0, 0, 0.5)"
            width="33%"
          />
        </div>
        <div className="power-wrap">
          <h3 id="powerWrapW">
            <span>Powered by</span>
            <img src={betFair} alt="Powered" />
          </h3>

          <div className="licence_embed">
            <iframe
              src="https://licensing.gaming-curacao.com/validator/?lh=7a83475c9e54450a218a18bd28e33fad&amp;template=seal"
              width="150"
              height="50"
              // style="border:none;"
            ></iframe>
          </div>

          <p>
            Skyexchange is operated by Sky Infotech N.V. a limited liability
            company incorporated under the laws of Curacao with company
            Registration number 152377 with registered office at Abraham de
            Veerstraat 9 , Curacao P.O Box 3421 and is licensed and regulated by
            the Curacao authority as the regulatory body responsible holding a
            (Sub-license with License number 365/JAZ Sub-License GLH-
            OCCHKTW0707072017 granted on 6.07.2017). Players are requested not
            to contact any untrusted sources for skyexchange.com accounts as
            this is an online site and they can only register independently
            without any agents. Only deposit through the account details
            generated by the system or provided by our official support team.
          </p>
        </div>
        <div className="browser-wrap">
          <img src={chromeIcon} />
          Our website works best in the newest and last prior version of these
          browsers: <br />
          Google Chrome. Firefox
        </div>
      </div>
      <div className="bottom-footer-col">
        <ul className="policy-link">
          <li>
            <span> Privacy Policy</span>
          </li>
          <li>
            <span> Terms and Conditions</span>
          </li>
          <li>
            <span> Rules and Regulations</span>
          </li>
          <li>
            <span> KYC</span>
          </li>
          <li>
            <span> Responsible Gaming</span>
          </li>
          <li>
            <span> About Us</span>
          </li>
          <li>
            <span> Self-exclusion Policy</span>
          </li>
          <li>
            <span> Underage Policy</span>
          </li>
        </ul>
        <div className="app-link">
          <img src={isMobile ? downIos : app} alt="" />
          <p>v1.11 - 2022-03-23 - 3.1MB</p>
        </div>
        <div className="extra-wrap">
          <div className="power-wrap-b">
            <span>Powered by</span>
            <img src={betFair} />
          </div>

          <div className="appdl-link-ios">
            <img src={app} alt="" />
            <p>v1.00 - 2019-04-10 - 0.4MB</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FooterComponent;
